<script>
    import Button from "../GeneralComponents/Button.svelte";
    import Inputs from "../GeneralComponents/Inputs.svelte";
  
    import {onSnapsBgyID, compareIDvalue, showAddModal } from "../BoundComponents/clickOutside";
    import { showPrintModel, formattedDate } from "./stateStore";

    //database calls and hooks
    import { auth, db } from "../../db/firebase";
    import { onSnapshot, addDoc, collection, serverTimestamp, increment, doc, deleteDoc, query, orderBy, setDoc } from "firebase/firestore";

    //handler to show add modal
    const toShowAddModal = () => {
        showAddModal.set(true)
    }
    
    //barangayID varStore
    const bgyVarStore = {
        completeName: "",
        address: "",
        birthdate: "",
        gender: "",
        height: "",
        weight: "",

    }

    //submit data to database
    const submitData = async() => {
        const colRef = collection(db, "barangayID");
        addDoc(colRef, {
            createdAt: serverTimestamp(),
            completeName: bgyVarStore.completeName.BINDTHIS,
            address: bgyVarStore.address.BINDTHIS,
            birthdate: bgyVarStore.birthdate.BINDTHIS,
            gender: bgyVarStore.gender.BINDTHIS,
            height: bgyVarStore.height.BINDTHIS,
            weight: bgyVarStore.weight.BINDTHIS,
            barangayCounter: increment(1),
            
        }).then(() => {
            showAddModal.set(false);
        })
    }

    //fetch data from database
    const colRef = collection(db, "barangayID");
    const q = query(colRef, orderBy("createdAt", "desc"))
    onSnapshot(q, (snapshots) => {
        let fbData = [];
        snapshots.docs.forEach(doc => {
            let data = {...doc.data(), id: doc.id};
            fbData = [data, ...fbData];
        })
        onSnapsBgyID.set(fbData);

    })

    //removeData from database
    const removeData = async(data) => {
        const docRef = doc(colRef, data);
        await deleteDoc(docRef)
        
    }

    //updateData from database
    const updateData = async(data) => {
        const docRef = doc(colRef, data);
        setDoc(docRef, {
            lastUpdated: serverTimestamp(),
            completeName: bgyVarStore.completeName.BINDTHIS,
            address: bgyVarStore.address.BINDTHIS,
            birthdate: bgyVarStore.birthdate.BINDTHIS,
            gender: bgyVarStore.gender.BINDTHIS,
            height: bgyVarStore.height.BINDTHIS,
            weight: bgyVarStore.weight.BINDTHIS,
        }, {merge:true})
    }

    //showModalComparison
    const editValueHandler = (data) => {
        compareIDvalue.set(data);
    }
</script>

<div class="m-2  mx-auto">
    <div class="min-h-[50vh] p-4">
        <div class="max-w-fit flex gap-2">
            <div class="">
                <Button TITLE="Add Barangay ID" on:click={toShowAddModal}/>
            </div>

            <div class="">
                <Button TITLE="Print" on:click={() => showPrintModel.set(true)}/>
            </div>
        </div>


        {#if $showPrintModel}
            <div class="fixed bottom-0 top-0 left-0 right-0 bg-white text-xs">

                <div class="mx-auto max-w-[1200px] mt-[20vh] p-10">
                    <div class="fixed bottom-0 right-0 p-10 ">
                        <div class="flex gap-2">
                            <div class="">
                                <Button TITLE="Print Now" on:click={() => print()}/>
                            </div>
                            <div class="">
                                <Button TITLE="Close" on:click={() => showPrintModel.set(false)}/>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mb-5 flex flex-col gap-2  ">
                        <p class=" "><b>Date: </b>{formattedDate}</p>
                        <p class=" "><b>Generated by:</b> Sn3 Barangay System</p>
                    </div>
                    
                    <div class="flex justify-center items-center">
                        <p class="w-full bg-[#272822] text-white p-2 border-2 font-bold">Name</p>
                        <p class="w-full bg-[#272822] text-white p-2 border-2 font-bold">Address</p>
                        <p class="w-[50%] bg-[#272822] text-white p-2 border-2 font-bold">Birthdate</p>
                        <p class="w-[50%] bg-[#272822] text-white p-2 border-2 font-bold">Gender</p>
                        <p class="w-[50%] bg-[#272822] text-white p-2 border-2 font-bold">Height</p>
                        <p class="w-[50%] bg-[#272822] text-white p-2 border-2 font-bold">Weight</p>
                        
                    </div>
                    {#each $onSnapsBgyID as val}
                    <div class="flex justify-center items-center">
                        <p class="w-full   p-2 border-2">{val.completeName}</p>
                        <p class="w-full   p-2 border-2">{val.address}</p>
                        <p class="w-[50%]   p-2 border-2">{val.birthdate}</p>
                        <p class="w-[50%]  p-2 border-2">{val.gender}</p>
                        <p class="w-[50%]  p-2 border-2">{val.height}</p>
                        <p class="w-[50%]  p-2 border-2">{val.weight}</p>
                    </div>
                    {/each}
                </div>
            </div>
            
        {/if}
        

        <div class="flex  justify-center items-center mt-2">
            <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Name</p>
            <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Address</p>
            <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Birthdate</p>
            <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Gender</p>
            <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Height</p>
            <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Weight</p>
            <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Option</p>
        </div>
        
        {#if $showAddModal}
        <div class="flex flex-col gap-2 bg-white p-4 max-w-fit mx-auto rounded-lg mt-2 absolute left-0 right-0 border-2 border-guiColor z-10">
            <p class="text-xl text-center font-bold p-2 text-slate-500">New Barangay ID</p>
            <div class="">
                <Inputs TITLE="Complete Name:" PLACEHOLDER="Complete Name" bind:this={bgyVarStore.completeName}/>
            </div>

            <div class="flex justify-center gap-2">
                <div class="">
                     <Inputs TITLE="Height" PLACEHOLDER="Height" bind:this={bgyVarStore.height}/>
                </div>
                <div class="">
                    <Inputs TITLE="Weight" PLACEHOLDER="Weight" bind:this={bgyVarStore.weight}/>
                </div>
            </div>

            <div class="flex justify-center gap-2">
                <div class="w-full">
                     <Inputs TITLE="Birthdate:" TYPE="date" bind:this={bgyVarStore.birthdate}/>
                </div>
                <div class="w-full">
                    <Inputs TITLE="Gender:" TYPE="cordion" bind:this={bgyVarStore.gender}/>
               </div>
              
            </div>

            <div class="">
                <Inputs TITLE="Complete Address:" PLACEHOLDER="Complete Address" bind:this={bgyVarStore.address}/>
            </div>
            
            <div class="flex gap-2">
                <Button TITLE="Submit" on:click={submitData}/>
                <Button TITLE="Cancel" on:click={()=>{showAddModal.set(false)}}/>
            </div>
        </div>
        {/if}
        <div class="">
            {#each $onSnapsBgyID as value, i}
            <div class="flex justify-center items-center ">
                <p class="w-full border-2 border-white bg-slate-100 p-2 ">{value.completeName}</p>
                <p class="w-full border-2 border-white bg-slate-100 p-2 ">{value.address}</p>
                <p class="w-full border-2 border-white bg-slate-100 p-2 ">{value.birthdate}</p>
                <p class="w-full border-2 border-white bg-slate-100 p-2 ">{value.gender}</p>
                <p class="w-full border-2 border-white bg-slate-100 p-2 ">{value.height}</p>
                <p class="w-full border-2 border-white bg-slate-100 p-2 ">{value.weight}</p>
                <div class="flex gap-2 w-full p-2 bg-slate-100">
                    <Button TITLE="Delete" COLOR="bg-redColor" on:click={removeData(value.id)}/>
                    <Button TITLE="Edit" on:click={()=>{editValueHandler(i)}}/>
                </div>
                {#if $compareIDvalue === i}
                    <div class="">
                        <div class="flex flex-col gap-2 bg-guiColor p-4 max-w-fit mx-auto rounded-lg mt-2 absolute left-0 right-0 border-2 border-slate-200 z-10">
                            <p class="text-xl text-center font-bold p-2 text-slate-500">Modify Values</p>
                            <div class="">
                                <Inputs TITLE="Complete Name:" PLACEHOLDER="Complete Name" bind:this={bgyVarStore.completeName}/>
                            </div>
                
                            <div class="flex justify-center gap-2">
                                <div class="">
                                    <Inputs TITLE="Height" PLACEHOLDER="Height" bind:this={bgyVarStore.height}/>
                                </div>
                                <div class="">
                                    <Inputs TITLE="Weight" PLACEHOLDER="Weight" bind:this={bgyVarStore.weight}/>
                                </div>
                            </div>
                
                            <div class="flex justify-center gap-2">
                                <div class="w-full">
                                    <Inputs TITLE="Birthdate:" TYPE="date" bind:this={bgyVarStore.birthdate}/>
                                </div>

                                <div class="w-full">
                                    <Inputs TITLE="Gender:" TYPE="cordion" bind:this={bgyVarStore.gender}/>
                                </div>
                            
                            </div>
                
                            <div class="">
                                <Inputs TITLE="Complete Address:" PLACEHOLDER="Complete Address" bind:this={bgyVarStore.address}/>
                            </div>
                            
                            <div class="flex gap-2">
                                <Button TITLE="Confirm Edit" on:click={updateData(value.id)}/>
                                <Button TITLE="Cancel" on:click={() => {compareIDvalue.set("")}}/>
                            </div>
                        </div>
                    </div>
                {/if}
            </div>
            {/each}

        </div>
        
    </div>

    
</div>