<script>
    import Button from "../GeneralComponents/Button.svelte";
    import Inputs from "../GeneralComponents/Inputs.svelte";

    import { showPrintModel } from "./stateStore";

    import { showAdd, onSnaps, compareValue } from "../BoundComponents/clickOutside";

    //database calls and hooks
    import { auth, db } from "../../db/firebase";
    import { addDoc, collection, serverTimestamp, onSnapshot, query, orderBy, increment, deleteDoc, doc, setDoc } from "firebase/firestore";

    //toggle show modal of add voter
    const showAddModal = () => {
        showAdd.set(true);
    }

    //handler for send data of addVoter
    const listOfVotersStore = {
        completeName: "",
        precintNum: "",
        completeAddress: "",
    }
    const addVoter = async() => {
       const colRef = collection(db, "votersList");
       await addDoc(colRef, {
            createdAt: serverTimestamp(),
            completeName: listOfVotersStore.completeName.BINDTHIS,
            precintNumber: listOfVotersStore.precintNum.BINDTHIS,
            completeAddress: listOfVotersStore.completeAddress.BINDTHIS,
            voterCounter: increment(1),
       }).then(() => {
            listOfVotersStore.completeName.BINDTHIS = "";
            listOfVotersStore.precintNum.BINDTHIS = "";
            listOfVotersStore.completeAddress.BINDTHIS = "";
       })
    }

    //database loop data
    const colRef = collection(db, "votersList");
    const q = query(colRef, orderBy("createdAt", "desc"))
    onSnapshot(q, (snapshots) => {
        let fbData = [];
        snapshots.docs.forEach(doc => {
            let data = {...doc.data(), id: doc.id}
            fbData = [data, ...fbData];
        })
        onSnaps.set(fbData);
    })

    //database remove data
    const removeData = async(data) => {
        const docRef = doc(colRef, data);
        await deleteDoc(docRef);
    }

    //database update data
    const updateData = async(data) => {
        const docRef = doc(colRef, data)
        setDoc(docRef, {
            lastUpdated: serverTimestamp(),
            completeName: listOfVotersStore.completeName.BINDTHIS,
            precintNumber: listOfVotersStore.precintNum.BINDTHIS,
            completeAddress: listOfVotersStore.completeAddress.BINDTHIS,
        }, {merge:true}).then(() => {
            listOfVotersStore.completeName.BINDTHIS = "";
            listOfVotersStore.precintNum.BINDTHIS = "";
            listOfVotersStore.completeAddress.BINDTHIS = "";
        })

    }

    //showEditModal
    const showEditModal = (i) => {
        compareValue.set(i)
    }

    //print data to external platforms like pdf etc
    const printFunc = () => {
        print();
    }
    
</script>

<div class="m-2 sm:max-w-[1200px] mx-auto">
    <div class="min-h-[50vh] p-4">
        <div class="max-w-fit mb-2 flex gap-2">
            <div class="">
                <Button TITLE="Add Voter" on:click={showAddModal}/>
            </div>

            <div class="">
                <Button TITLE="Print" on:click={() => showPrintModel.set(true)}/>
            </div>
        </div>

        {#if $showPrintModel}
            <div class="fixed bottom-0 top-0 left-0 right-0 bg-white ">

                <div class="mx-auto max-w-[1000px] mt-[20vh] p-10">
                    <div class="fixed bottom-0 right-0 p-10 ">
                        <div class="flex gap-2">
                            <div class="">
                                <Button TITLE="Print Now" on:click={printFunc}/>
                            </div>
                            <div class="">
                                <Button TITLE="Close" on:click={() => showPrintModel.set(false)}/>
                            </div>
                        </div>
                    </div>
                    <div class="mb-5 flex flex-col gap-2  ">
                        <p class=" "><b>Date:</b> Nov, 1, 1996</p>
                        <p class=" "><b>Generated by:</b> Sn3 Barangay System</p>
                    </div>
                    <div class="flex "> 
                        <div class="">
                            <p class="p-2 border-b-2 border-l-2 ">Precint # </p>
                            <p class="p-2 border-b-2 border-l-2 ">667</p>
                            <p class="p-2 border-b-2 border-l-2 ">55</p>
                        </div>

                        <div class="">
                            <p class="p-2 border-b-2 border-l-2 ">Name </p>
                            <p class="p-2 border-b-2 border-l-2 ">Peter PanicPeter PanicPeter Panic asdasdasd</p>
                            <p class="p-2 border-b-2 border-l-2 ">Mang jose</p>
                        </div>
            
                       
            
                        <div class="">
                            <p class="p-2 border-b-2 border-l-2 ">Address </p>
                            <p class="p-2 border-b-2 border-l-2 ">Bualacan , 545St malate </p>
                            <p class="p-2 border-b-2 border-l-2 ">Bualacan , 545St malate Laguna</p>
                        </div>
                    </div>
                </div>
            </div>
            
            
        {/if}
        
       
        <!--ADD voters-->
        {#if $showAdd}
        <div class="flex flex-col gap-2 bg-guiColor p-4 max-w-fit mx-auto rounded-lg mt-2 absolute left-0 right-0 border-2 border-slate-200">
            <p class="text-xl text-center font-bold p-2 text-slate-500">Add New Voter</p>
            <div class="flex gap-2 justify-center">
                <div class="">
                    <Inputs TITLE="Name:" PLACEHOLDER="Complete Name" bind:this={listOfVotersStore.completeName}/>
                </div>
                <div class="">
                    <Inputs TITLE="PRECINT#:" PLACEHOLDER="Precint Number" TYPE="number" bind:this={listOfVotersStore.precintNum}/>
                </div>
                <div class="">
                    <Inputs TITLE="ADDRESS:" PLACEHOLDER="Complete Address" bind:this={listOfVotersStore.completeAddress}/>
                </div>
            </div>
            
            <div class="flex gap-2">
                <Button TITLE="Submit" on:click={addVoter}/>
                <Button TITLE="Close" on:click={()=>{showAdd.set(false)}}/>
            </div>
            
        </div>
        {/if}
        <!--End of add voters-->

        <div class="">

            <div class="flex  justify-center items-center">
                <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Name</p>
                <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Precint#</p>
                <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Address</p>
                <p class="text-xl sm:text-2xl font-bold text-left w-full bg-slate-200 p-2 border-2 border-white">Option</p>

                
                

            </div>
            {#each $onSnaps as value , i}
                <div class="">
                    <div class="flex justify-center items-center ">
                        <p class="w-full border-2 border-white bg-slate-100 p-2 ">{value.completeName}</p>
                        <p class="w-full border-2 border-white bg-slate-100 p-2 ">{value.precintNumber}</p>
                        <p class="w-full border-2 border-white bg-slate-100 p-2 ">{value.completeAddress}</p>
                        <div class="flex gap-2 w-full p-2 bg-slate-100">
                            <Button TITLE="Delete" COLOR="bg-redColor" on:click={()=>{removeData(value.id)}}/>
                            <Button TITLE="Edit" on:click={()=>{showEditModal(i)}}/>
                        </div>
                        
                    </div>
                 

                    {#if $compareValue === i}
                    <div class="flex flex-col bg-guiColor gap-2 p-4 max-w-fit mx-auto rounded-lg mt-2 absolute left-0 right-0 border-2 border-slate-200 z-10">
                        <p class="text-xl text-center font-bold p-2 text-slate-500">Modify Values</p>
                        <div class="flex gap-2 justify-center">
                            <div class="">
                                <Inputs TITLE="Name:" PLACEHOLDER="Complete Name" bind:this={listOfVotersStore.completeName}/>
                            </div>
                            <div class="">
                                <Inputs TITLE="PRECINT#:" PLACEHOLDER="Precint Number" TYPE="number" bind:this={listOfVotersStore.precintNum}/>
                            </div>
                            <div class="">
                                <Inputs TITLE="ADDRESS:" PLACEHOLDER="Complete Address" bind:this={listOfVotersStore.completeAddress}/>
                            </div>
                        </div>
                        
                        <div class="flex gap-2">
                            <Button TITLE="Confirm Edit" on:click={() => {updateData(value.id)}}/>
                            <Button TITLE="Close" on:click={showEditModal}/>
                        </div>
                        
                    </div>
                    {/if}
                </div>
            {/each}
        </div>
        
    </div>
</div>
